import {
  cr1,
  cr3,
  cr4,
  cr5,
  pcardOne,
  cr6,
  cr7,
  cr8,
  cr9,
  c115,
  cr10,
} from "@/utils/assets";

export const carouselContent = [
  {
    key: 1,
    value: "AI",
    title: "ai Listing",
    subTitle: "Snap It & Sell It, That’s Literally It",
    description:
      "No more battling text boxes. Point your camera at what you want to sell; we do the rest. Let ai handle those boring details while you, well, get on with life.",
    btnTitle: "Snap & Sell Now! →",
    image: cr1,
    imageWidth: 585,
    imageHeight: 540,
    imageMobileWidth: 200,
    imageMobileHeight: 400,
    imageTabWidth: 300,
    imageTabHeight: 600,
    positionTab: {
      right: 0,
      bottom: 0,
    },
    position: {
      right: 0,
      bottom: 0,
    },
    btnMaxWidth: "max-w-[318px]",
    c1: true,
    c2: true,
    c3: true,
    c4: true,
  },
  {
    key: 2,
    value: "ZERO",
    title: "Zero Seller Fees",
    subTitle: "All Profit, No Sneaky Deductions!",
    description:
      "Because you should keep every penny for that next must have find or that big night out.",
    btnTitle: "Start Earning, Fee-Free →",
    image: pcardOne,
    imageWidth: 500,
    imageHeight: 540,
    imageMobileWidth: 200,
    imageMobileHeight: 400,
    imageTabWidth: 200,
    imageTabHeight: 600,
    positionTab: {
      right: 10,
      top: 16,
    },
    position: {
      right: 10,
      top: 14,
    },
    btnMaxWidth: "max-w-[380px]",
    c5: true,
    c6: true,
    c7: true,
  },
  {
    key: 3,
    value: "SELLER",
    title: "ai Seller Tools",
    subTitle: "Your Secret Listing Weapon.",
    description:
      "We polish your photos, punch up your descriptions, and get your gear noticed so your item stands out like a rare gem.",
    btnTitle: "Pimp My Listing! →",
    image: cr3,
    imageWidth: 252,
    imageHeight: 508,
    imageMobileWidth: 90,
    imageMobileHeight: 400,
    imageTabWidth: 150,
    imageTabHeight: 600,
    positionTab: {
      right: 20,
      bottom: 0,
    },
    position: {
      right: 40,
      bottom: 0,
    },
    btnMaxWidth: "max-w-[318px]",
    c8: true,
    c9: true,
    c10: true,
    c21: true,
  },
  {
    key: 4,
    value: "EFFORT",
    title: "Effortless Shipping",
    subTitle: "Pack, Post, Done.",
    description:
      "Seamless, integrated shipping labels. No queueing at the post office or messing about with addresses, send it off and watch the kudos roll in.",
    btnTitle: "Ship It in a Snap →",
    image: cr4,
    imageWidth: 585,
    imageHeight: 540,
    imageMobileWidth: 200,
    imageMobileHeight: 400,
    imageTabWidth: 250,
    imageTabHeight: 600,
    positionTab: {
      right: 10,
      top: 16,
    },
    position: {
      right: 10,
      bottom: 10,
    },
    btnMaxWidth: "max-w-[318px]",
    c22: true,
    c23: true,
    c24: true,
    c25: true,
  },
  {
    key: 5,
    value: "AUTO",
    title: "ai Automated Negotiation",
    subTitle: "Let Our Bots Haggle. You Just Collect the Cash.",
    description:
      "Skip the awkward back and forth. ai gets you a fair price without all that ‘Is this still available?’ nonsense.",
    btnTitle: "Activate Robo Negotiation →",
    image: cr5,
    imageWidth: 300,
    imageHeight: 680,
    imageMobileWidth: 90,
    imageMobileHeight: 400,
    imageTabWidth: 150,
    imageTabHeight: 600,
    positionTab: {
      right: 20,
      bottom: 0,
    },
    position: {
      right: 40,
      bottom: 0,
    },
    btnMaxWidth: "max-w-[390px]",
    c26: true,
    c27: true,
    c28: true,
  },
];

export const carouselSteps = [
  "ai Listing",
  "Zero Seller Fees",
  "ai Seller Tools",
  "Effortless Shipping",
  "ai Negotiations",
];

export const carouselContentTwo = [
  {
    key: 1,
    value: "EASY",
    title: "",
    subTitle: "Easy Store Setup",
    description:
      "Connect your POS, upload inventory, and start selling online in minutes",
    btnTitle: "Create your store! →",
    image: cr10,
    imageWidth: 483,
    imageHeight: 348,
    imageMobileWidth: 200,
    imageMobileHeight: 400,
    imageTabWidth: 200,
    imageTabHeight: 600,
    positionTab: {
      right: 10,
      bottom: 0,
    },
    position: {
      right: 20,
      bottom: 0,
    },
    btnMaxWidth: "max-w-[318px]",
    c29: true,
    c30: true,
    c31: true,
  },
  {
    key: 2,
    value: "POWER",
    title: "",
    subTitle: "Powerful Management",
    description:
      "Full retail system with integrated POS, inventory control, and customer tracking",
    btnTitle: "Experience Now! →",
    image: cr7,
    imageWidth: 580,
    imageHeight: 500,
    imageMobileWidth: 200,
    imageMobileHeight: 400,
    imageTabWidth: 200,
    imageTabHeight: 600,
    positionTab: {
      right: 0,
      bottom: 0,
    },
    position: {
      right: 0,
      bottom: 0,
    },
    btnMaxWidth: "max-w-[318px]",
  },
  {
    key: 3,
    value: "PRO",
    title: "",
    subTitle: "Professional Tools",
    description:
      "ai-powered listings, smart pricing, and automated customer communications",
    btnTitle: "Try for FREE! →",
    image: c115,
    imageWidth: 580,
    imageHeight: 500,
    imageMobileWidth: 200,
    imageMobileHeight: 400,
    imageTabWidth: 200,
    imageTabHeight: 600,
    positionTab: {
      right: 0,
      bottom: 0,
    },
    position: {
      right: 0,
      bottom: 0,
    },
    btnMaxWidth: "max-w-[318px]",
    c32: true,
    c33: true,
    c34: true,
    c35: true,
  },
  {
    key: 4,
    value: "UNLIMITED",
    title: "",
    subTitle: "Unlimited Growth",
    description:
      "Expand your reach online while managing everything from one free dashboard",
    btnTitle: "Boost your Growth! →",
    image: cr8,
    imageWidth: 700,
    imageHeight: 500,
    imageMobileWidth: 200,
    imageMobileHeight: 400,
    imageTabWidth: 250,
    imageTabHeight: 600,
    positionTab: {
      right: 0,
      bottom: 0,
    },
    position: {
      right: 0,
      bottom: 0,
    },
    btnMaxWidth: "max-w-[330px]",
  },
];

export const carouselStepsTwo = [
  "Easy Store Setup",
  "Powerful Management",
  "Professional Tools",
  "Unlimited Growth",
];
